### ISSUE TITLE
deno run -A npm:create-hono my-app crashes on execution. 

### ISSUE THREAD

**Issue by WrathZA** [honojs/create-hono#31]
Testing https://github.com/honojs/create-hono/issues/21 

`PS C:\dev> deno --version
deno 1.42.0 (release, x86_64-pc-windows-msvc)
v8 12.3.219.9
typescript 5.4.3
PS C:\dev> deno run -A -L debug npm:create-hono test-app
DEBUG RS - deno::args::package_json:146 - No package.json file found
DEBUG RS - deno::cache::cache_db:130 - Opening cache C:\Users\mille\AppData\Local\deno\dep_analysis_cache_v1...
DEBUG RS - deno::cache::cache_db:130 - Opening cache C:\Users\mille\AppData\Local\deno\node_analysis_cache_v1...
DEBUG RS - deno_npm::resolution::graph:972 - <package-req> - Resolved create-hono@* to create-hono@0.6.2
DEBUG RS - deno::npm::managed:301 - Resolved package folder of create-hono@0.6.2 to C:\Users\mille\AppData\Local\deno\npm\registry.npmjs.org\create-hono\0.6.2
DEBUG RS - deno::js:10 - Deno isolate init with snapshots.
DEBUG RS - deno::worker:178 - main_module file:///C:/Users/mille/AppData/Local/deno/npm/registry.npmjs.org/create-hono/0.6.2/bin
create-hono version 0.6.2
✔ Using target directory … test-app
? Which template do you want to use?
> aws-lambda
  bun
  cloudflare-pages
  cloudflare-workers
  deno
  fastly
  lambda-edge
(Use arrow keys to reveal more choices)error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Symbol(Deno.internal.rid)')
    at TTY.#read (ext:deno_node/internal_binding/stream_wrap.ts:220:45)
    at TTY.readStart (ext:deno_node/internal_binding/stream_wrap.ts:90:17)
    at _tryReadStart (node:net:276:30)
    at ReadStream._read (node:net:856:7)
    at ReadStream.Readable.read (ext:deno_node/_stream.mjs:2999:16)
    at ReadStream.read (node:net:789:34)
    at resume_ (ext:deno_node/_stream.mjs:3349:16)
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:33:15)
    at eventLoopTick (ext:core/01_core.js:165:29)`

**Comment by WrathZA** [comment]
Hello, 
Is there an expectation that you would want to support windows? 
and if so, to what degree?

**Comment by ryuapp** [comment]
Hello @WrathZA 
This seems to be a bug from Deno 1.42.0.
It works in version 1.41.2.
```sh
deno upgrade --version 1.41.2
```
I also use Windows, so I don't know if it occurs on other OS.

**Comment by ryuapp** [comment]
This issue has already been fixed on Deno.
I think it will work in the next version.

Ref: denoland/deno#23107

**Comment by yusukebe** [comment]
Great!
