### ISSUE TITLE
Bun - TypeError: Cannot call a class constructor without |new|

### ISSUE THREAD

**Issue by rokf** [honojs/create-hono#33]
Hi,

I'm trying to run the following

```sh
bunx create-hono coffee-store
```

and get the following output 

```
create-hono version 0.6.3
✔ Using target directory … coffee-store
TypeError: Cannot call a class constructor without |new|
```

and it hangs - doesn't finish.

My `bun` version is `1.1.3`.

I haven't (yet) tried if the same thing happens with other runtimes / package managers.

Anything else I can do to provide additional input?

Thanks!

**Comment by rokf** [comment]
I've tried it with **node** `v21.7.3` and it worked. Looks like it has something to do with Bun.

**Comment by yusukebe** [comment]
Hi @rokf 

Hmm. Weird. It works fine in my env:

![CleanShot 2024-04-18 at 07 42 13@2x](https://github.com/honojs/create-hono/assets/10682/e545622d-3216-4660-8c09-e20be82a9b42)

**Comment by rokf** [comment]
I've upgraded Bun to version `1.1.4`.

With that change both `bunx create-hono@latest example` (with `@latest`) and `bunx create-hono example2` now work.

I'm on macOS Sonoma 14.4.1 (M1 Max chip).

I'll mark this issue as resolved.
