### ISSUE TITLE
Download a template after all choices

### ISSUE THREAD

**Issue by ryuapp** [honojs/create-hono#36]
Currently, we have to choose whether to install dependencies after cloning a template, which is not good UX.
After making all your choices, we need to download it.

**Comment by yusukebe** [comment]
Hi @ryuapp 

I think the current flow is not bad for DX. Do you mean like this?

![CleanShot 2024-04-29 at 13 11 18@2x](https://github.com/honojs/create-hono/assets/10682/9d016f6c-ed7a-4b30-a700-44dd13e89556)

**Comment by yusukebe** [comment]
> I don't like waiting for cloning the template while my selecting.

Ahhh, I see. That will be good.

**Comment by MathurAditya724** [comment]
Can I work on this?

**Comment by yusukebe** [comment]
@MathurAditya724 

yes!
