### ISSUE TITLE
npm create hono@latest sets compatibility date in the past in wrangler.toml

### ISSUE THREAD

**Issue by rita3ko** [honojs/create-hono#58]
### What version of Hono are you using?

create-hono version 0.9.3

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

npm create hono@latest my-hono-project
select "cloudflare workers" 
go to wrangler.toml

### What is the expected behavior?

compatibility date is set to current date

### What do you see instead?

compatibility_date = "2023-12-01"

**Comment by yusukebe** [comment]
Hey @6km @MathurAditya724 @fzn0x or others

Is anyone interested in implementing this feature?

**Comment by MathurAditya724** [comment]
Yup, I can

**Comment by yusukebe** [comment]
@MathurAditya724 Cool! I think you can create it as a `hook`.

**Comment by MathurAditya724** [comment]
Yes, that's what I am thinking. Looks easy

**Comment by yusukebe** [comment]
Hi @rita3ko 

Thanks to @MathurAditya724 , the current date can be set as a compatibility date. I've released the new version, `0.10.0`, which includes the feature. You can try it if you like. Thanks for the issue.
