### ISSUE TITLE
Support `deno install`

### ISSUE THREAD

**Issue by ryuapp** [honojs/create-hono#73]
It will be available from Deno 2.0.
HonoX partially works on Deno, so it's worth supporting.

**Comment by yusukebe** [comment]
Hi @ryuapp 

Deno will introduce `deno install,` which is good! Is there anything we can do before GA?

**Comment by ryuapp** [comment]
Hello @yusukebe 

We can already try `deno install` with `deno upgrade rc`, so it can be implemented.
It would be even better if there is a feature that does not display depending on the version.
